name: Basic-Schulung
on: 
  workflow_dispatch:

jobs: 
 build: 
  name: My fist Action
  runs-on: ubuntu-latest
  steps: 
  - uses: actions/checkout@v1
  - uses: ./actions-a
    with:
      MY_NAME: Jan
    
